# Generated by Django 4.0.6 on 2023-06-09 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='user_assoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
